name = "Baozongwi Signal"
license = "GPL-3.0-only"
description = "An independent Hugo theme for security notes, CTF writeups, and personal logs"
homepage = "https://baozongwi.xyz"

tags = ["blog", "responsive", "security", "ctf", "personal"]

features = [
    "opengraph",
    "widgets",
    "table of contents",
]

min_version = "0.123.0"

[author]
name = "baozongwi"
homepage = "https://github.com/baozongwi"
